language: c
sudo: false

cache:
  directories:
  - $HOME/.stack

addons:
  apt:
    packages:
    - libgmp-dev

env:
  - STACK_ARGS=""
  - STACK_ARGS="--resolver lts-2"
  - STACK_ARGS="--resolver lts-3"
  - STACK_ARGS="--resolver nightly"

before_install:
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - stack --no-terminal setup

install:
  - stack $STACK_ARGS setup --no-terminal
  - stack $STACK_ARGS build --only-snapshot --no-terminal

script:
  - stack $STACK_ARGS test --pedantic --no-terminal --skip-ghc-check --haddock
