language: c
sudo: false

cache:
  directories:
  - $HOME/.stack

addons:
  apt:
    packages:
    - libgmp-dev

env:
  - STACK_ARGS="" STACK_YAML=stack-travis.yaml
  - STACK_ARGS="--resolver lts-2" STACK_YAML=stack-lts2.yaml
  - STACK_ARGS="--resolver nightly" STACK_YAML=stack-travis.yaml

before_install:
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
  - stack $STACK_ARGS setup --no-terminal
  - stack $STACK_ARGS build --only-snapshot --no-terminal --haddock

script:
  - stack $STACK_ARGS test --pedantic --no-terminal --skip-ghc-check --haddock
