language: generic
sudo: false

cache:
  directories:
    - $HOME/.stack
    - $HOME/.cabal
    - $HOME/.ghc

matrix:
  fast_finish: true
  include:
    - env: BUILD=stack STACK_BUILD_MODE="test" STACK_BUILD_ARGS="--bench --no-run-benchmarks" STACK_ARGS="--haddock" PUBLISH_DOCS="yes" STACK_YAML=stack.yaml
      compiler: ": #stack 8.0.1"
      addons: {apt: {packages: [libgmp-dev]}}
    - env: BUILD=stack STACK_BUILD_MODE="test" STACK_BUILD_ARGS="--bench --no-run-benchmarks" STACK_ARGS="--resolver nightly" STACK_YAML=stack.yaml
      compiler: ": #stack 8.0.2"
      addons: {apt: {packages: [libgmp-dev]}}
    - env: BUILD=cabal CABALVER=1.24 GHCVER=8.0.1
      compiler: ": #GHC 8.0.1"
      addons: {apt: {packages: [cabal-install-1.24,ghc-8.0.1], sources: [hvr-ghc]}}

before_install:
  - mkdir -p ~/.local/bin
  - unset CC
  - set -e; case "$BUILD" in
       stack)
         export PATH=$HOME/.local/bin:/opt/ghc/$GHCVER/bin:$PATH;
         travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack';;
       cabal)
         export PATH=$HOME/.cabal/bin:/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH;;
    esac

install:
  - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
  - set -e; case "$BUILD" in
      stack)
        stack $STACK_ARGS setup --no-terminal;
        if [ "$PUBLISH_DOCS" = "yes" ]; then stack $STACK_ARGS install --no-terminal hscolour; fi;
        stack $STACK_ARGS build --fast --only-snapshot --no-terminal --haddock;;
      cabal)
        travis_retry cabal update -v;
        sed -i 's/^jobs:/-- jobs:/' ${HOME}/.cabal/config;
        cabal new-build --dep --enable-tests --disable-benchmarks -j2;;
    esac

script:
  - set -e; case "$BUILD" in
      stack)
        stack $STACK_ARGS $STACK_BUILD_MODE --pedantic --fast --no-terminal --skip-ghc-check $STACK_BUILD_ARGS ;;
      cabal)
        echo "Doing a cabal build ...";
        cabal version;
        cabal new-build --enable-tests --disable-benchmarks -j2 ;;
    esac

deploy:
  on:
    condition: "$PUBLISH_DOCS = yes"
    branch: master
  provider: s3
  bucket: spockdocs
  skip_cleanup: true
  acl: public_read
  region: eu-central-1
  local_dir: .stack-work/install/x86_64-linux/lts-7.12/8.0.1/doc/
  access_key_id:
    secure: ScZQy2B54CnU26bGZivMS6IMQYnKbfOnjspkoRpUcuYU7tOc+IB4OHxSlribidtcyCel0PEARJzU2dlIf8Vn1XuVrj32K4gXzS3Mg7HBEKoeI1aioRwSp4z9VtQLBVDyzJzMIPqqKYGGSNByOjyXGUtxeFLuSK2yRfkoQe8CPGc=
  secret_access_key:
    secure: c61LIVSE3b2fFbwa2PVh27EaeY/dmEUmyM0wbrBWv09NWDrIfM12jQJ6R9VlIXgS44hRga9TrplVCiU5RUgaV7KuPfLyFOPfym1G3FGdKXjJWYmLugCxjJ4VhHAoggln6hrwe8WELCe/yVBVRcwjx/9J6cKz0SuIQb1fODDAOEk=
