flags: {}
packages:
  - Spock/
  - Spock-api/
  - Spock-api-server/
  - Spock-core/
  - reroute/
  - location:
      git: https://github.com/agrafix/hvect
      commit: 6c2a970d0c78523d377f3cd7343dbaa11349a587
    extra-dep: true
resolver: lts-7.12
extra-deps:
  - superbuffer-0.2.0.1
