# Site settings
title: Spock Haskell Web Framework
email: mail@athiemann.net
description: > 
  Spock is a lightweight Haskell web framework inspired by Ruby's Sinatra. It provides a full
  toolbox including everything to get a quick start into web programming using Haskell.
baseurl: "" 
url: "https://www.spock.li" 
enforce_ssl: www.spock.li

twitter_username: agrafix
github_username:  agrafix

# Build settings
markdown: kramdown

gems:
  - jekyll-redirect-from
